### ISSUE TITLE
steps.cache should accept multiple patterns

### ISSUE THREAD

**Issue by JackKelly-Bellroy** [regadas/github-actions-dhall#17]
The `hashFiles` function in the Github Actions expression language can support multiple patterns: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#hashfiles

It would be nice for the cache step in this repo to support that also, by taking a `List Text` instead of a single `Text`. I started to prepare a PR for this but got lost in apparent duplication: what is the design intent between `steps/cache.dhall` and `steps/actions/cache.dhall`? `dhall hash` says that they're identical. Is one deprecated?

**Comment by regadas** [comment]
Hi @JackKelly-Bellroy yup steps/cache.dhall are deprecated ... They should have been removed actually! I'll remove them, thanks for preparing a PR 👍
