### ISSUE TITLE
Scala example doesn't seem to work

### ISSUE THREAD

**Issue by gvolpe** [regadas/github-actions-dhall#2]
Hi,

I gave this a try and after running the following command:

```
$ curl https://raw.githubusercontent.com/regadas/github-actions-dhall/master/examples/scala.dhall | dhall-to-yaml
```
I got the following error:

```
Error: Invalid input

(stdin):27:28:
   |
27 | in  GithubActions.Workflow::{
   |                            ^^^
unexpected ":{<newline>    ,"
expecting expression or whitespace
```

Here's my `shell.nix` specifying my dependencies:

```nix
let
  pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs-channels/archive/nixos-20.03.tar.gz") {};
  stdenv = pkgs.stdenv;

in stdenv.mkDerivation rec {
  name = "neutron";
  buildInputs = [
    pkgs.dhall-json # v1.6.2
    pkgs.openjdk # v1.8.0_222
    pkgs.sbt  # v1.3.8
  ];
}
```

Is this behavior expected using `dhall-json-v1.6.2`?

**Comment by regadas** [comment]
Hi @gvolpe interesting 🤔 ... I'm using `1.6.4` and I'm not seeing that behavior. I would guess it should have worked as well with `1.6.2`. Let see if i can replicate it.

**Comment by gvolpe** [comment]
Wow, thanks for the quick reply! I can also try to pull in `1.6.4` and see if I can get it working, I was just confident it should also work with `1.6.2`, given my pinned Nix version.

**Comment by regadas** [comment]
seems to be working as well with `1.6.2`.

On a second look, you seem to be using the stable channel and I think that pulls `1.3.0`, `1.6.2` is on the `unstable` though, can that older version have a regression? (I don't use nixos ... yet 😄 )

**Comment by gvolpe** [comment]
Oh right! Sorry about that, I pasted the wrong Nix URL, I'm now on a different pinned channel which brings `dhall-json-1.6.2` and I got a different kind of error.

```
↳ ./../package.dhall sha256:b42b062af139587666185c6fb72cc2994aa85a30065324174760b7d29a9d81c9

Error: Missing file ./../package.dhall

2│       ../package.dhall sha256:b42b062af139587666185c6fb72cc2994aa85a30065324174760b7d29a9d81c9

(stdin):2:7
```

Does this mean I need to check out the entire project to make it work? Or I am just doing things the wrong way? :smile:  

I have this:

```dhall
let GithubActions =
      https://github.com/regadas/github-actions-dhall/blob/master/package.dhall sha256:b42b062af139587666185c6fb72cc2994aa85a30065324174760b7d29a9d81c9
```

**Comment by gvolpe** [comment]
Nevermind! Using `https://raw.githubusercontent.com/regadas/github-actions-dhall/master/package.dhall` instead works, thanks!

**Comment by regadas** [comment]
No problem! Although it's still strange that the freezed import didn't work 🤔.

**Comment by gvolpe** [comment]
Hey @regadas , it's me again :smile: 

Do you have any examples of the Scala generated YAML file used in some project? Github actions doesn't seem to like the generated YAML, it doesn't pick it up. 

Here's an example: https://github.com/gvolpe/pfps-examples/pull/51

**Comment by regadas** [comment]
Hi @gvolpe!

Yup created one example right now https://github.com/regadas/scala-gha-dhall.

**Comment by gvolpe** [comment]
Awesome, thanks!
