### ISSUE TITLE
Type RunsOn too strict

### ISSUE THREAD

**Issue by sengaya** [regadas/github-actions-dhall#8]
First of all: Awesome work, many thanks!

I think the type of [RunsOn](https://github.com/regadas/github-actions-dhall/blob/master/types/RunsOn.dhall) is too strict as it only permits one of the github provided runners.

There is the possibility to define a matrix for the runners, e.g. like that https://github.com/sengaya/aws-micro-cli/blob/master/.github/workflows/main.yml#L18-L21 so i would need to put something like `${{ matrix.os }}` for `runs-on`.

Also there is the possibility for custom runners. I have no experience with this but I guess that's also not possible with the current type restriction.

**Comment by regadas** [comment]
Hi @sengaya, sorry for late reply!

Yeah good point! I have seen more cases of using a runner matrix. We need to allow that use case for sure. Let me get back to you.
